package robot

type CachedInfo struct {
	Uin                        int    `json:"Uin"`
	Wxid                       string `json:"Wxid"`
	Pwd                        string `json:"Pwd"`
	Uuid                       string `json:"Uuid"`
	Aeskey                     string `json:"Aeskey"`
	NotifyKey                  string `json:"NotifyKey"`
	DeviceidStr                string `json:"Deviceid_str"`
	DeviceidByte               string `json:"Deviceid_byte"`
	DeviceType                 string `json:"DeviceType"`
	ClientVersion              int    `json:"ClientVersion"`
	DeviceName                 string `json:"DeviceName"`
	NickName                   string `json:"NickName"`
	HeadUrl                    string `json:"HeadUrl"`
	Email                      string `json:"Email"`
	Alais                      string `json:"Alais"`
	Mobile                     string `json:"Mobile"`
	Mmtlsip                    string `json:"Mmtlsip"`
	MmtlsHost                  string `json:"MmtlsHost"`
	Sessionkey                 string `json:"Sessionkey"`
	Sessionkey2                string `json:"Sessionkey_2"`
	Autoauthkey                string `json:"Autoauthkey"`
	Autoauthkeylen             int    `json:"Autoauthkeylen"`
	Clientsessionkey           string `json:"Clientsessionkey"`
	Serversessionkey           string `json:"Serversessionkey"`
	HybridEcdhPrivkey          any    `json:"HybridEcdhPrivkey"`
	HybridEcdhPubkey           any    `json:"HybridEcdhPubkey"`
	HybridEcdhInitServerPubKey any    `json:"HybridEcdhInitServerPubKey"`
	Loginecdhkey               string `json:"Loginecdhkey"`
	Cooike                     string `json:"Cooike"`
	LoginMode                  string `json:"LoginMode"`
	MarsHost                   string `json:"MarsHost"`
	Proxy                      any    `json:"Proxy"`
	MmtlsKey                   struct {
		GVEJHIROBh   string `json:"GVEJHIROBh"`
		W6D1LM       int    `json:"W6d1lM"`
		Wpdpiuv      string `json:"Wpdpiuv"`
		U650A0QuwEG  int    `json:"U650a0QuwEG"`
		IHqUrE2EE    string `json:"IHqUrE2EE"`
		Xx67J0       int    `json:"Xx67j0"`
		IH2WafCq     string `json:"IH__2wafCq"`
		K8Lw7W       int    `json:"K8lw7w"`
		FpcOaCmsNO   any    `json:"FpcOaCmsNO"`
		PPWpADdGuFHB int    `json:"PPWpADdGuFHB"`
		SlTxYh       int    `json:"SlTxYh"`
		X3MmtMlzSlW  string `json:"X3MmtMlzSlW"`
		SZp5UQ21PD   int    `json:"SZp5_UQ21pD"`
		A21H7H       string `json:"A21H_7h"`
		Ir6Noa       string `json:"Ir6noa"`
		QVfIdfw      string `json:"QVfIdfw"`
		Mmaz0LSj     string `json:"Mmaz0lSj"`
		ZDV2Xzn      any    `json:"ZDV2Xzn"`
		WxuKtZneSb   any    `json:"WxuKtZneSb"`
		Bg0ChqSWSv   string `json:"Bg0chqSWSv"`
		C0X2GS       string `json:"C0_X2GS"`
		RK1TWT58     string `json:"RK1TWT58"`
		OOS0VQVfB    string `json:"OOS0vQVfB"`
		Ps63XxlibW   string `json:"Ps63xxlibW"`
		ChmlEwbaQ    string `json:"ChmlEwbaQ"`
		VayI1HTA     any    `json:"VayI1HTA"`
		HT7BBEEl     any    `json:"HT7bBEEl"`
		CEZe6HtueZ   any    `json:"CEZe6htueZ"`
		KjDdoOh9     any    `json:"KjDdoOh9"`
		ReoRMAvMyd   any    `json:"ReoRMAvMyd"`
		UjErK5I8     any    `json:"UjErK5i8"`
		CDGFzW90     any    `json:"CDGFzW90"`
		INRS2QIq     string `json:"INRS2qIq"`
		K3JRPJn      string `json:"K3JRPJn"`
		AxUp7F       string `json:"AxUp7F"`
		BfBhafa      string `json:"BfBhafa"`
		A37CFpHR     string `json:"A37CFpHR"`
		P7XEdt       string `json:"P7XEdt_"`
		KrIqx71L     string `json:"KrIqx7_1L"`
		GcEv06       string `json:"GcEv06"`
		VsbjOPtj     int    `json:"VsbjOPtj"`
	} `json:"MmtlsKey"`
	DeviceToken struct {
	} `json:"DeviceToken"`
	SyncKey       string `json:"SyncKey"`
	Data62        string `json:"Data62"`
	RomModel      string `json:"RomModel"`
	Imei          string `json:"Imei"`
	SoftType      string `json:"SoftType"`
	OsVersion     string `json:"OsVersion"`
	RsaPublicKey  string `json:"RsaPublicKey"`
	RsaPrivateKey string `json:"RsaPrivateKey"`
	Dns           any    `json:"Dns"`
	LoginRsaVer   int    `json:"LoginRsaVer"`
	EnableService bool   `json:"EnableService"`
	Ecpukey       any    `json:"ecpukey"`
	Ecprkey       any    `json:"ecprkey"`
	Ticket        string `json:"Ticket"`
	LoginDataInfo struct {
		Type        int    `json:"Type"`
		UserName    string `json:"UserName"`
		PassWord    string `json:"PassWord"`
		NewPassWord string `json:"NewPassWord"`
		LoginData   string `json:"LoginData"`
		Ticket      string `json:"Ticket"`
		NewType     int    `json:"NewType"`
		Language    string `json:"Language"`
	} `json:"LoginDataInfo"`
	DeviceInfo any `json:"DeviceInfo"`
	LoginDate  int `json:"LoginDate"`
}
